import { port, ports } from "./_helpers";
import type { DeviceTemplate } from "../types";

export const templates: DeviceTemplate[] = [
  // ── Media Servers ────────────────────────────────────────────────
  {
    id: "c0a80101-00b8-4000-8000-000000000184",
    deviceType: "media-server",
    label: "Disguise d3 4x4pro",
    manufacturer: "Disguise",
    modelNumber: "d3 4x4pro",
    referenceUrl: "https://www.disguise.one/en/products/legacy-products/",
    searchTerms: ["disguise", "d3", "4x4pro", "media server"],
    slots: [
      { id: "d3-4x4-vfc-a", label: "VFC Slot A", defaultCardId: "vfc-card-dp12", slotFamily: "disguise-vfc" },
      { id: "d3-4x4-vfc-b", label: "VFC Slot B", defaultCardId: "vfc-card-dp12", slotFamily: "disguise-vfc" },
      { id: "d3-4x4-vfc-c", label: "VFC Slot C", defaultCardId: "vfc-card-dp12", slotFamily: "disguise-vfc" },
      { id: "d3-4x4-vfc-d", label: "VFC Slot D", defaultCardId: "vfc-card-dp12", slotFamily: "disguise-vfc" },
    ],
    ports: [
      port("GUI Output", "displayport", "output"),
      port("Genlock In", "genlock", "input"),
      port("1GbE 1", "ethernet", "bidirectional"),
      port("1GbE 2", "ethernet", "bidirectional"),
      port("DMX Out", "dmx", "output"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-00b9-4000-8000-000000000185",
    deviceType: "media-server",
    label: "Disguise d3 Solo",
    manufacturer: "Disguise",
    modelNumber: "d3 Solo",
    referenceUrl: "https://www.disguise.one/en/products/legacy-products/",
    searchTerms: ["disguise", "d3", "solo", "media server", "compact"],
    slots: [
      { id: "d3-solo-vfc-a", label: "VFC Slot A", defaultCardId: "vfc-card-dp12", slotFamily: "disguise-vfc" },
    ],
    ports: [
      port("GUI Output", "displayport", "output"),
      port("Genlock In", "genlock", "input"),
      port("1GbE 1", "ethernet", "bidirectional"),
      port("1GbE 2", "ethernet", "bidirectional"),
      port("USB", "usb", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-00ba-4000-8000-000000000186",
    deviceType: "media-server",
    label: "Dataton WATCHPAX 60",
    manufacturer: "Dataton",
    modelNumber: "WATCHPAX 60",
    referenceUrl: "https://www.dataton.com/watchpax/watchpax-64",
    searchTerms: ["dataton", "watchpax", "watchout", "media server"],
    ports: [
      ...ports("HDMI Out", "hdmi", "output", 4),
      port("HDMI In", "hdmi", "input"),
      port("Ethernet 1", "ethernet", "bidirectional"),
      port("Ethernet 2", "ethernet", "bidirectional"),
      port("USB", "usb", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-00bb-4000-8000-000000000187",
    deviceType: "media-server",
    label: "Dataton WATCHPAX 40",
    manufacturer: "Dataton",
    modelNumber: "WATCHPAX 40",
    referenceUrl: "https://www.dataton.com/watchpax/watchpax-64",
    searchTerms: ["dataton", "watchpax", "watchout", "media server", "compact"],
    ports: [
      port("HDMI Out 1", "hdmi", "output"),
      port("HDMI Out 2", "hdmi", "output"),
      port("HDMI In", "hdmi", "input"),
      port("Ethernet 1", "ethernet", "bidirectional"),
      port("Ethernet 2", "ethernet", "bidirectional"),
      port("USB", "usb", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
  // Infrastructure new devices
  {
    id: "c0a80101-010a-4000-8000-000000000342",
    deviceType: "media-server",
    category: "media-servers",
    label: "Disguise VX 4+",
    manufacturer: "Disguise",
    modelNumber: "VX 4+",
    referenceUrl: "https://www.disguise.one/en/products/vx-range/",
    searchTerms: ["disguise", "vx4", "media server", "d3"],
    slots: [
      { id: "vfc-slot-a", label: "VFC Slot A", defaultCardId: "vfc-card-hdmi20", slotFamily: "disguise-vfc" },
      { id: "vfc-slot-b", label: "VFC Slot B", defaultCardId: "vfc-card-hdmi20", slotFamily: "disguise-vfc" },
      { id: "vfc-slot-c", label: "VFC Slot C", defaultCardId: "vfc-card-hdmi20", slotFamily: "disguise-vfc" },
      { id: "vfc-slot-d", label: "VFC Slot D", defaultCardId: "vfc-card-hdmi20", slotFamily: "disguise-vfc" },
    ],
    ports: [
      port("GUI Output", "displayport", "output"),
      port("Genlock In", "genlock", "input"),
      port("10GbE SFP+ 1", "ethernet", "bidirectional", "sfp"),
      port("10GbE SFP+ 2", "ethernet", "bidirectional", "sfp"),
      port("1GbE 1", "ethernet", "bidirectional"),
      port("1GbE 2", "ethernet", "bidirectional"),
      port("USB", "usb", "bidirectional", "usb-a"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-010c-4000-8000-000000000344",
    deviceType: "media-server",
    category: "media-servers",
    label: "Disguise VX 1",
    manufacturer: "Disguise",
    modelNumber: "VX 1",
    referenceUrl: "https://www.disguise.one/en/products/vx-range/",
    searchTerms: ["disguise", "vx1", "media server", "d3"],
    slots: [
      { id: "vx1-vfc-a", label: "VFC Slot A", defaultCardId: "vfc-card-hdmi20", slotFamily: "disguise-vfc" },
    ],
    ports: [
      port("GUI Output", "displayport", "output"),
      port("Genlock In", "genlock", "input"),
      port("1GbE 1", "ethernet", "bidirectional"),
      port("1GbE 2", "ethernet", "bidirectional"),
      port("USB", "usb", "bidirectional", "usb-a"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-010d-4000-8000-000000000345",
    deviceType: "media-server",
    category: "media-servers",
    label: "Disguise VX 2",
    manufacturer: "Disguise",
    modelNumber: "VX 2",
    referenceUrl: "https://www.disguise.one/en/products/vx-range/",
    searchTerms: ["disguise", "vx2", "media server", "d3"],
    slots: [
      { id: "vx2-vfc-a", label: "VFC Slot A", defaultCardId: "vfc-card-hdmi20", slotFamily: "disguise-vfc" },
      { id: "vx2-vfc-b", label: "VFC Slot B", defaultCardId: "vfc-card-hdmi20", slotFamily: "disguise-vfc" },
    ],
    ports: [
      port("GUI Output", "displayport", "output"),
      port("Genlock In", "genlock", "input"),
      port("10GbE SFP+ 1", "ethernet", "bidirectional", "sfp"),
      port("10GbE SFP+ 2", "ethernet", "bidirectional", "sfp"),
      port("1GbE 1", "ethernet", "bidirectional"),
      port("1GbE 2", "ethernet", "bidirectional"),
      port("USB", "usb", "bidirectional", "usb-a"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-010e-4000-8000-000000000346",
    deviceType: "media-server",
    category: "media-servers",
    label: "Disguise VX 3",
    manufacturer: "Disguise",
    modelNumber: "VX 3",
    referenceUrl: "https://www.disguise.one/en/products/vx-range/",
    searchTerms: ["disguise", "vx3", "media server", "d3"],
    slots: [
      { id: "vx3-vfc-a", label: "VFC Slot A", defaultCardId: "vfc-card-hdmi20", slotFamily: "disguise-vfc" },
      { id: "vx3-vfc-b", label: "VFC Slot B", defaultCardId: "vfc-card-hdmi20", slotFamily: "disguise-vfc" },
      { id: "vx3-vfc-c", label: "VFC Slot C", defaultCardId: "vfc-card-hdmi20", slotFamily: "disguise-vfc" },
    ],
    ports: [
      port("GUI Output", "displayport", "output"),
      port("Genlock In", "genlock", "input"),
      port("10GbE SFP+ 1", "ethernet", "bidirectional", "sfp"),
      port("10GbE SFP+ 2", "ethernet", "bidirectional", "sfp"),
      port("1GbE 1", "ethernet", "bidirectional"),
      port("1GbE 2", "ethernet", "bidirectional"),
      port("USB", "usb", "bidirectional", "usb-a"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-010f-4000-8000-000000000347",
    deviceType: "media-server",
    category: "media-servers",
    label: "Disguise GX 1",
    manufacturer: "Disguise",
    modelNumber: "GX 1",
    referenceUrl: "https://www.disguise.one/en/products/gx-range/",
    searchTerms: ["disguise", "gx1", "media server", "gpu"],
    slots: [
      { id: "gx1-vfc-a", label: "VFC Slot A", defaultCardId: "vfc-card-hdmi20", slotFamily: "disguise-vfc" },
    ],
    ports: [
      port("GUI Output", "displayport", "output"),
      port("Genlock In", "genlock", "input"),
      port("1GbE 1", "ethernet", "bidirectional"),
      port("1GbE 2", "ethernet", "bidirectional"),
      port("USB", "usb", "bidirectional", "usb-a"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-0110-4000-8000-000000000348",
    deviceType: "media-server",
    category: "media-servers",
    label: "Disguise GX 2",
    manufacturer: "Disguise",
    modelNumber: "GX 2",
    referenceUrl: "https://www.disguise.one/en/products/gx-range/",
    searchTerms: ["disguise", "gx2", "media server", "gpu"],
    slots: [
      { id: "gx2-vfc-a", label: "VFC Slot A", defaultCardId: "vfc-card-dp12", slotFamily: "disguise-vfc" },
      { id: "gx2-vfc-b", label: "VFC Slot B", defaultCardId: "vfc-card-dp12", slotFamily: "disguise-vfc" },
    ],
    ports: [
      port("GUI Output", "displayport", "output"),
      port("Genlock In", "genlock", "input"),
      port("10GbE SFP+ 1", "ethernet", "bidirectional", "sfp"),
      port("10GbE SFP+ 2", "ethernet", "bidirectional", "sfp"),
      port("1GbE 1", "ethernet", "bidirectional"),
      port("1GbE 2", "ethernet", "bidirectional"),
      port("USB", "usb", "bidirectional", "usb-a"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-0111-4000-8000-000000000349",
    deviceType: "media-server",
    category: "media-servers",
    label: "Disguise GX 2C",
    manufacturer: "Disguise",
    modelNumber: "GX 2C",
    referenceUrl: "https://www.disguise.one/en/products/gx-range/",
    searchTerms: ["disguise", "gx2c", "media server", "gpu", "compact"],
    slots: [
      { id: "gx2c-vfc-a", label: "VFC Slot A", defaultCardId: "vfc-card-hdmi20", slotFamily: "disguise-vfc" },
      { id: "gx2c-vfc-b", label: "VFC Slot B", defaultCardId: "vfc-card-hdmi20", slotFamily: "disguise-vfc" },
    ],
    ports: [
      port("GUI Output", "displayport", "output"),
      port("Genlock In", "genlock", "input"),
      port("10GbE SFP+ 1", "ethernet", "bidirectional", "sfp"),
      port("10GbE SFP+ 2", "ethernet", "bidirectional", "sfp"),
      port("1GbE 1", "ethernet", "bidirectional"),
      port("1GbE 2", "ethernet", "bidirectional"),
      port("USB", "usb", "bidirectional", "usb-a"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-0112-4000-8000-000000000350",
    deviceType: "media-server",
    category: "media-servers",
    label: "Disguise GX 3",
    manufacturer: "Disguise",
    modelNumber: "GX 3",
    referenceUrl: "https://www.disguise.one/en/products/gx-range/",
    searchTerms: ["disguise", "gx3", "media server", "gpu"],
    slots: [
      { id: "gx3-vfc-a", label: "VFC Slot A", defaultCardId: "vfc-card-dp14", slotFamily: "disguise-vfc" },
      { id: "gx3-vfc-b", label: "VFC Slot B", defaultCardId: "vfc-card-dp14", slotFamily: "disguise-vfc" },
    ],
    ports: [
      port("GUI Output", "displayport", "output"),
      port("Genlock In", "genlock", "input"),
      port("10GbE SFP+ 1", "ethernet", "bidirectional", "sfp"),
      port("10GbE SFP+ 2", "ethernet", "bidirectional", "sfp"),
      port("1GbE 1", "ethernet", "bidirectional"),
      port("1GbE 2", "ethernet", "bidirectional"),
      port("USB", "usb", "bidirectional", "usb-a"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-010b-4000-8000-000000000343",
    deviceType: "media-server",
    category: "media-servers",
    label: "Disguise EX 2",
    manufacturer: "Disguise",
    modelNumber: "EX 2",
    referenceUrl: "https://www.disguise.one/en/products/ex-range/",
    searchTerms: ["disguise", "ex2", "media server", "d3"],
    ports: [
      port("DP Out 1", "displayport", "output"),
      port("DP Out 2", "displayport", "output"),
      port("NDI In", "ndi", "input"),
      port("Genlock In", "genlock", "input"),
      port("Ethernet 1", "ethernet", "bidirectional"),
      port("Ethernet 2", "ethernet", "bidirectional"),
      port("USB", "usb", "bidirectional", "usb-a"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-010c-4000-8000-000000000344",
    deviceType: "media-server",
    category: "media-servers",
    label: "Dataton WATCHPAX 64",
    manufacturer: "Dataton",
    modelNumber: "WATCHPAX 64",
    referenceUrl: "https://www.dataton.com/watchpax/watchpax-64",
    searchTerms: ["dataton", "watchpax", "watchout", "media server"],
    ports: [
      port("DP Out 1", "displayport", "output"),
      port("DP Out 2", "displayport", "output"),
      port("DP Out 3", "displayport", "output"),
      port("DP Out 4", "displayport", "output"),
      port("Ethernet 1", "ethernet", "bidirectional"),
      port("Ethernet 2", "ethernet", "bidirectional"),
      port("USB", "usb", "bidirectional", "usb-a"),
      port("AC Power", "power", "input"),
    ],
  },
];
